<a href="https://colab.research.google.com/github/xiepeijia/Machine-Learning-note/blob/master/numpy%E7%9A%84%E8%BF%90%E7%AE%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# 逻辑运算

In [2]:
score = np.random.randint(40, 100, (10, 5))
score

array([[53, 92, 46, 63, 99],
       [73, 48, 78, 97, 83],
       [83, 77, 61, 60, 94],
       [86, 49, 98, 60, 81],
       [40, 89, 87, 70, 45],
       [45, 66, 95, 88, 97],
       [43, 85, 87, 51, 61],
       [99, 83, 45, 53, 94],
       [85, 53, 95, 74, 83],
       [68, 62, 59, 79, 53]])

In [0]:
test_score = score[:4, :]

In [4]:
test_score

array([[53, 92, 46, 63, 99],
       [73, 48, 78, 97, 83],
       [83, 77, 61, 60, 94],
       [86, 49, 98, 60, 81]])

In [5]:
test_score > 60

array([[False,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True, False,  True]])

In [0]:
a = [1,2,3,3]

In [0]:
# a > 2  # 不可以

In [0]:
# a + 2  # 不可以

In [9]:
a * 2

[1, 2, 3, 3, 1, 2, 3, 3]

In [0]:
test_score[test_score > 60] = 100

In [11]:
test_score

array([[ 53, 100,  46, 100, 100],
       [100,  48, 100, 100, 100],
       [100, 100, 100,  60, 100],
       [100,  49, 100,  60, 100]])

# 通用判断函数

In [12]:
test_score2 = score[7:, :]
test_score2

array([[99, 83, 45, 53, 94],
       [85, 53, 95, 74, 83],
       [68, 62, 59, 79, 53]])

In [13]:
np.all(test_score2> 60)

False

In [14]:
np.any(test_score2> 60)

True

# np.where（三元运算符）

In [15]:
test_score2

array([[99, 83, 45, 53, 94],
       [85, 53, 95, 74, 83],
       [68, 62, 59, 79, 53]])

In [16]:
np.where(test_score2 > 60, 1, 0)

array([[1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 1, 0]])

In [17]:
np.where(np.logical_and(test_score2 > 60, test_score2 < 90), 1, 0)

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0]])

In [18]:
np.where(np.logical_or(test_score2 < 60, test_score2 > 90), 1, 0)

array([[1, 0, 1, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1]])

# 统计运算

In [19]:
test_score2

array([[99, 83, 45, 53, 94],
       [85, 53, 95, 74, 83],
       [68, 62, 59, 79, 53]])

In [20]:
np.max(test_score2, axis=0)

array([99, 83, 95, 79, 94])

In [21]:
np.max(test_score2, axis=1)

array([99, 95, 79])

In [22]:
np.min(test_score2, axis=1)

array([45, 53, 53])

In [23]:
test_score2

array([[99, 83, 45, 53, 94],
       [85, 53, 95, 74, 83],
       [68, 62, 59, 79, 53]])

In [24]:
np.argmax(test_score2, axis=0)

array([0, 0, 1, 2, 0])

In [25]:
np.argmin(test_score2, axis=0)

array([2, 1, 0, 0, 2])

# 数组的运算

In [26]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [27]:
a + 2

array([3, 4, 5, 6, 7])

In [28]:
a * 2

array([ 2,  4,  6,  8, 10])

In [0]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [0]:
# arr1 + arr2

In [31]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [0]:
arr3 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [33]:
arr2 * arr3

array([[ 1,  4,  9, 16],
       [ 9, 16, 25, 36]])

In [34]:
arr4 = np.array([[2], [3]])  # 两行一列
arr4

array([[2],
       [3]])

In [35]:
arr3  # 两行四列

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [36]:
arr3 + arr4

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [37]:
arr5 = np.array([[2,2,2,2], [3,3,3,3]])
arr5

array([[2, 2, 2, 2],
       [3, 3, 3, 3]])

In [38]:
arr3 +arr5

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [39]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape
# (4, 1)

arr2 = np.array([1,2,3])
arr2.shape
# (3,)

arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [0]:
a = np.array([2,3,4,5])
b = np.array([3,4,5,6,7])

In [0]:
# a + b  # 不可以

In [42]:
a = np.ones([4,1])
a

array([[1.],
       [1.],
       [1.],
       [1.]])

In [43]:
b = np.ones([2, 4, 3])
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [0]:
# a + b

# 矩阵运算

In [0]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([[0.7], [0.3]])

In [46]:
a 

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [47]:
b

array([[0.7],
       [0.3]])

In [48]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [0]:
# a * b  # 数组间相乘和矩阵相乘是不同的!!!

In [50]:
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [51]:
np.dot(a, 10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [0]:
# np.matmul(a, 10) # 不可以