<a href="https://colab.research.google.com/github/xiepeijia/Machine-Learning-note/blob/master/pandas%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

# Series

## 创建

In [0]:
pd.Series(np.arange(5))

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [0]:
pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [0]:
count = pd.Series({"red":100, "blue":200, "green":20})
count

blue     200
green     20
red      100
dtype: int64

## 属性

In [0]:
count.index

Index(['blue', 'green', 'red'], dtype='object')

In [0]:
count.values

array([200,  20, 100])

# DataFrame

## 创建

In [0]:
pd.DataFrame(np.random.randint(2, 300, [3, 4]))

0    1    2    3
0  136  136   20  240
1   58  108   71  122
2  130  248  206  199

In [0]:
score = pd.DataFrame(np.random.randint(40, 100, [10, 5]))
score

0   1   2   3   4
0  54  65  83  99  99
1  80  42  97  91  49
2  97  88  94  60  75
3  73  51  85  69  95
4  83  89  45  46  64
5  42  59  94  87  61
6  52  70  72  72  42
7  59  85  91  44  80
8  93  42  72  41  88
9  88  71  98  99  58

In [0]:
# 构造行索引序列
subjects = ["语文", "数学", "英语", "政治", "体育"]

# 构造列索引
stu = ["同学"+str(i) for i in range(score.shape[0])]

# 添加索引
score = pd.DataFrame(np.random.randint(40, 100, [10, 5]), index=stu, columns=subjects)

In [0]:
score.shape[0]

10

In [0]:
score

语文  数学  英语  政治  体育
同学0  54  99  40  41  92
同学1  51  94  63  93  62
同学2  79  62  75  89  99
同学3  53  75  84  91  40
同学4  41  59  73  51  90
同学5  80  65  91  97  89
同学6  42  62  88  70  94
同学7  67  85  92  63  81
同学8  98  82  81  76  54
同学9  97  72  66  58  76

## 属性

In [0]:
score.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [0]:
score.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [0]:
score.values

array([[54, 99, 40, 41, 92],
       [51, 94, 63, 93, 62],
       [79, 62, 75, 89, 99],
       [53, 75, 84, 91, 40],
       [41, 59, 73, 51, 90],
       [80, 65, 91, 97, 89],
       [42, 62, 88, 70, 94],
       [67, 85, 92, 63, 81],
       [98, 82, 81, 76, 54],
       [97, 72, 66, 58, 76]])

In [0]:
score.shape

(10, 5)

In [0]:
score.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   54   51   79   53   41   80   42   67   98   97
数学   99   94   62   75   59   65   62   85   82   72
英语   40   63   75   84   73   91   88   92   81   66
政治   41   93   89   91   51   97   70   63   76   58
体育   92   62   99   40   90   89   94   81   54   76

In [0]:
score.head(4)

语文  数学  英语  政治  体育
同学0  54  99  40  41  92
同学1  51  94  63  93  62
同学2  79  62  75  89  99
同学3  53  75  84  91  40

In [0]:
score.tail()

语文  数学  英语  政治  体育
同学5  80  65  91  97  89
同学6  42  62  88  70  94
同学7  67  85  92  63  81
同学8  98  82  81  76  54
同学9  97  72  66  58  76

In [0]:
score.head()

语文  数学  英语  政治  体育
同学0  54  99  40  41  92
同学1  51  94  63  93  62
同学2  79  62  75  89  99
同学3  53  75  84  91  40
同学4  41  59  73  51  90

## 修改索引

In [0]:
# 构造列索引
stu = ["同学__"+str(i) for i in range(score.shape[0])]

score.index = stu

In [0]:
score

语文  数学  英语  政治  体育
同学__0  54  99  40  41  92
同学__1  51  94  63  93  62
同学__2  79  62  75  89  99
同学__3  53  75  84  91  40
同学__4  41  59  73  51  90
同学__5  80  65  91  97  89
同学__6  42  62  88  70  94
同学__7  67  85  92  63  81
同学__8  98  82  81  76  54
同学__9  97  72  66  58  76

In [0]:
# score.index[2] = '同学++2'  # 索引值的修改,不支持单个值

## 重设索引

In [0]:
score.reset_index(drop=True)

语文  数学  英语  政治  体育
0  54  99  40  41  92
1  51  94  63  93  62
2  79  62  75  89  99
3  53  75  84  91  40
4  41  59  73  51  90
5  80  65  91  97  89
6  42  62  88  70  94
7  67  85  92  63  81
8  98  82  81  76  54
9  97  72  66  58  76

## 以某列值为新的索引

In [0]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

In [0]:
df

month  sale  year
0      1    55  2012
1      4    40  2014
2      7    84  2013
3     10    31  2014

In [0]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [0]:
mi = df.set_index(["year", "month"])
mi

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

# MultiIndex(panel)

## 属性

In [0]:
mi.index

MultiIndex(levels=[[2012, 2013, 2014], [1, 4, 7, 10]],
           labels=[[0, 2, 1, 2], [0, 1, 2, 3]],
           names=['year', 'month'])

In [0]:
mi.index.names

FrozenList(['year', 'month'])

## 创建

In [0]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))

MultiIndex(levels=[[1, 2], ['blue', 'red']],
           labels=[[0, 0, 1, 1], [1, 0, 1, 0]],
           names=['number', 'color'])

## panel

In [0]:
p = pd.Panel(data=np.arange(24).reshape(4,3,2),
                 items=list('ABCD'),
                 major_axis=pd.date_range('20130101', periods=3),
                 minor_axis=['first', 'second'])

In [0]:
data=np.arange(24).reshape(4,3,2)
data

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 3 (major_axis) x 2 (minor_axis)
Items axis: A to D
Major_axis axis: 2013-01-01 00:00:00 to 2013-01-03 00:00:00
Minor_axis axis: first to second

In [0]:
p["A", :, :]

first  second
2013-01-01      0       1
2013-01-02      2       3
2013-01-03      4       5

In [0]:
p["A":"C", "20130102", :]

A  B   C
first   2  8  14
second  3  9  15